name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - dask
  - netcdf4
  - bottleneck
  - matplotlib
  - regionmask
  - cartopy
  - seaborn
  - scipy
  - cmocean
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - matplotx
  - cfgrib
  - pip
  - plotly
  - xeofs
  - nbconvert
  - ipywidgets
  - pip:
      - antlr4-python3-runtime==4.7.2
      - cacholote==0.3.1
      - cads-toolbox==0.0.2b0
      - cdsapi==0.6.1
      - cf-units==3.2.0
      - cgul==0.0.4
      - coucal==0.0.1b3
      - emohawk==0.0.4b0
      - greenlet==2.0.2
      - pydantic==1.10.7
      - python-dotenv==1.0.0
      - sqlalchemy==2.0.14
      - structlog==23.1.0
